import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  metadataBase: new URL("https://audio-shots.vercel.app"),
  title: "Creators Page",
  description: "Generated by create next app",
  openGraph: {
    title: "Creators Page",
    description: "Generated by create next app",
    url: "https://audio-shots.vercel.app/",
    siteName: "AudioShots",
    type: "website",
    images: [
      {
        url: "/preview.png",
        width: 1223,
        height: 630,
        alt: "AudioShots OG Preview",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Creators Page",
    description: "Generated by create next app",
    images: ["/preview.png"],
  },
  icons: {
    icon: "/favicon.ico",
  },
};

export const viewport = {
  width: "device-width",
  initialScale: 1,
  themeColor: "#0C0C0C",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
